apiVersion: v1
kind: Template
metadata:
  name: my-namespace
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: ${name_namespace}
    labels:
      name: "${environnement}"
    annotations:
      openshift.io/node-selector: site=${site}"
      openshift.io/node-selector: zone=${zone}"
      openshift.io/description: "Pods du projet ${name_namespace} sera deployé au niveau du site ${site} de la zone ${zone}"
parameters:
- description: "Le nom du namespace"
  name: name_namespace
- description: "Label name au niveau du namespace"
  name: label
- description: "Zone de deploiement des projets au niveau de ce namespace"
  name: zone
- description: "Site de deploiement des projets au niveau de ce namespace"
  name: site
- description: "Environnement à provisionner (ETUDE,TEST,PREPROD,PROD)"
  name: environnement