# environnent : dev,prd
env: dev
# message d'acceuil
message: hello prd
CONNECT_BOOTSTRAP_SERVERS: l203ed2066.mousquetaires.com:9092,l203ed2066.mousquetaires.com:9093,l203ed2066.mousquetaires.com:9094
CONNECT_REST_ADVERTISED_HOST_NAME: l203ed2066.mousquetaires.com
CONNECT_REST_PORT: '8083'
CONNECT_GROUP_ID: multiplier-sink
CONNECT_CLIENT_ID: l203ed2066.mousquetaires.com
CONNECT_CONFIG_STORAGE_TOPIC: talaria_config_multiplier-sink
CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '1'
CONNECT_CONFIG_STORAGE_PARTITIONS: '1'
CONNECT_STATUS_STORAGE_TOPIC: talaria_status_multiplier-sink
CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '1'
CONNECT_STATUS_STORAGE_PARTITIONS: '1'
CONNECT_OFFSET_STORAGE_TOPIC: talaria_offset_multiplier-sink
CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '2'
CONNECT_OFFSET_STORAGE_PARTITIONS: '1'
CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
CONNECT_KEY_CONVERTER_SCHEMAS_ENABLED: 'false'
CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://l203ed2066.mousquetaires.com:8081'
CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
CONNECT_LOG4J_LOGGERS: org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR,fr.stime.hermes=DEBUG
CONNECT_ZOOKEEPER_CONNECT: l203ed2066.mousquetaires.com:2181,l203ed2066.mousquetaires.com:22181,l203ed2066.mousquetaires.com:32181/hermes
CONNECT_PLUGIN_PATH: /etc/kafka-connect/jars

