apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-03-01T16:59:00Z
  creationTimestamp: null
  generation: 2
  name: consul
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: consul:1.0.0
    generation: 2
    importPolicy: {}
    name: 1.0.0
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
