apiVersion: v1

kind: ConfigMap
metadata:
  name: conf.properties
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Values.apps.app_1.name }}
data:
{{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}
