apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: consul
  name: consul-2
spec:
  replicas: 3
  selector:
    app: consul
    deploymentconfig: consul-2
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consul
        deploymentconfig: consul-2
    spec:
      containers:
      - args:
        - agent
        - -ui
        - -data-dir=$(data_dir)
        - -client=0.0.0.0
        - -bootstrap-expect=$(bootstrap_expect)
        - -server
        - -bind=$(POD_IP_2)
        - -config-file=$(config_file)
        - -config-dir=$(config_dir)
        - -encrypt=$(GOSSIP_ENCRYPTION_KEY)
        - -rejoin
        - -retry-join=consul-1.consul.svc
        - -retry-join=consul-3.consul.svc
        - -disable-host-node-id
        env:
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: gossip-encryption-key
              name: consul
        - name: POD_IP_2
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: data_dir
          value: /tmp/consul/data
        - name: bootstrap_expect
          value: "3"
        - name: config_file
          value: /consul/config/server.json
        - name: config_dir
          value: /etc/consul.d
        image: consul:1.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
        name: consul
        ports:
        - containerPort: 8300
          name: server
          protocol: TCP
        - containerPort: 8301
          name: serflan-tcp
          protocol: TCP
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8302
          name: serfwan-tcp
          protocol: TCP
        - containerPort: 8302
          name: serfwan-udp
          protocol: UDP
        - containerPort: 8400
          name: rpc-port
          protocol: TCP
        - containerPort: 8500
          name: api-port
          protocol: TCP
        - containerPort: 8600
          name: consuldns-tcp
          protocol: TCP
        - containerPort: 8600
          name: consuldns-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health/state/any
            port: 8500
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /consul/config
          name: config
        - mountPath: /etc/tls
          name: tls
        - mountPath: /etc/consul.d
          name: conf-service
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: consulsa
      serviceAccountName: consulsa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: consul
        name: config
      - name: tls
        secret:
          defaultMode: 420
          secretName: consul
      - configMap:
          defaultMode: 420
          name: app.d
        name: conf-service
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - consul
      from:
        kind: ImageStreamTag
        name: consul:1.0.0
        namespace: consul
    type: ImageChange
  - type: ConfigChange
